# Generated by Django 6.0.5 on 2026-05-17 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_routinetemplate_routineitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='exercise_videos/'),
        ),
    ]
