# Generated by Django 6.0.5 on 2026-05-19 13:57

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_exercise_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='video_file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage, upload_to='exercise_videos/'),
        ),
    ]
