# Generated by Django 6.0.5 on 2026-05-19 17:44

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_alter_exercise_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='video_file',
            field=models.FileField(blank=True, max_length=500, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage, upload_to='exercise_videos/'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
