# Generated by Django 6.0.5 on 2026-05-21 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='has_been_onboarded',
            new_name='has_seen_onboarded',
        ),
    ]
