# Generated by Django 6.0.5 on 2026-05-21 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0008_rename_has_been_onboarded_userprofile_has_seen_onboarded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='has_seen_onboarded',
            new_name='has_seen_onboarding',
        ),
    ]
