# Generated by Django 6.0.5 on 2026-05-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0009_rename_has_seen_onboarded_userprofile_has_seen_onboarding'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activity_level',
            field=models.CharField(blank=True, choices=[('SEDENTARY', 'Sedentary (Little to no exercise)'), ('LIGHT', 'Light (Exercise 1-3 times/week)'), ('MODERATE', 'Moderate (Exercise 3-5 times/week)'), ('ACTIVE', 'Active (Heavy exercise 6 times/week)'), ('VERY_ACTIVE', 'Very Active (Physical job + heavy exercise)')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='goal',
            field=models.CharField(blank=True, choices=[('CUT', 'Lose Fat'), ('MAINTAIN', 'Maintain Weight'), ('BULK', 'Build Muscle')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='height_cm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='target_calories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='target_carps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='target_fats',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='target_protein',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weight_kg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
