# Generated by Django 6.0.5 on 2026-05-25 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0010_userprofile_activity_level_userprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='target_carps',
            new_name='target_carbs',
        ),
    ]
