# Generated by Django 6.0.5 on 2026-06-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0012_custommeal_dailyfoodlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyfoodlog',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
