# Generated by Django 6.0.5 on 2026-07-13 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0013_dailyfoodlog_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyfoodlog',
            name='date',
            field=models.DateField(db_index=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='workoutsessison',
            name='date',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
    ]
